### PR TITLE
281332 update toc dev guide

### PR DESCRIPTION
**Pull request by osisoft-mbishop**
Hi guys. Can I please get a reivew on my work for ticket [281332](https://dev.azure.com/osieng/engineering/_workitems/edit/281332)?

 I updated the TOC for the Developer's Guide to be alphabetical to match the TOC work we did for the API Reference (which we also alphabetized). I'd like you to confirm that I've indeed alphabetized the Developer's guide TOC, spelled everything correctly, etc.

Here's an [output preview](https://osisoft-dev.zoominsoftware.io/bundle/ocs-281332-update-toc-dev-guide/page/developer-guide/dev-guide-introduction.html).

Exceptions to the rule that *should not* be alphabetized:

* **Developer guide > Samples**. We want Samples to be at the bottom.
* **Developer guide > Data views > Data views stream and asset examples**. Same idea. We want samples at the bottom.
* **Developer guide > Data views > Define a data view > {subtopics}**. These topics are listed in a sequential order and therefore aren't alphabetized.

Thanks! Please ping if you need any clarifications.

### CODE REVIEW

**Comment by jasnames** [comment]
Topics under Sequential Data Store aren't alphabetized. I can see that the quick start should be first, but are the rest sequential?

Also, I'm not sure if this is within the scope of this, but there are many disagreements with TOC entries and topic titles:
- Asset and asset types / topic title is just "Assets"
- Asset-centric data / topic title is "Assets Centric Data"
- Asset search / topic title is "Asset Search Criteria"
- Asset status / topic title is "Asset and Asset Type Status"
- Resolved asset / topic title is "Resolved Asset Metadata"
- Recommended workflow - Get data view data / TOC has a dash, topic title has a colon
- Preview data view / topic title is "Preview data view API"
- OMF ingress specification / topic title is "Use OSIsoft Message Format with OSIsoft Cloud Services"
- Quick Start SDS / topic title is "Quick Start: Sequential Data Store" (also start shouldn't be capitalized in TOC)
- Streams write data / topic title is "Write data"
- Streams read data / topic title is "Read data"
- UoM and quantities / topic title is "Units of measure and quantities"

**Comment by KNyce71** [comment]
The only thing that I have to add is Assest-centric data is singular in the TOC but in the topic, it's plural (Assets Centric Data). Again, this also speaks to the TOC/topic disagreements mentioned by @jasnames. 

As long as the disagreements between the TOC and topics are out of scope and the SDS information is sequential (which based on a quick read, it appears to be), I don't see any additional issues.

**Comment by cmanhard** [comment]
We alphabetized the API section - not 100% clear to me that the developer guide should be totally alphabetized.  The former is more like a reference document - so it is easier to find things in specific order - the latter is more like a instruction book - so topics are generally covered in a logical order.

**Comment by osisoft-mbishop** [comment]
Thanks for commenting on this @cmanhard, I should have run this by you before doing the work. I assumed we should make the API Reference/Dev Guide match, but based on what you're saying, I'll likely just kill the PR. Let me run it by @osisoft-rabrego to hear his opinion.

**Pull request closed without merging**
