### PR TITLE
Operations - Remove Non-Docupipe Docs

### PR DESCRIPTION
**Pull request by tommarkosi**

### CODE REVIEW

**Review by GiselleLeeOSI — COMMENTED** [review]
Hi Thomas, is billing cycle no longer an API?

**Comment by tommarkosi** [comment]
It's in the usage query controller: https://github.com/osisoft/OCS-Docs/blob/DocuPipe-operations/content/api-reference/operations/operations-usage-query.md#list-tenant-billing-cycles

**Comment by GiselleLeeOSI** [comment]
Do you want me to review, approve and merge? Are there DocuPipe-generated .md in this branch already?

**Comment by tommarkosi** [comment]
I'm still waiting for one of the 4 PRs that point to this repository to finish (Metrics), the other 3 are there.

**Comment by GiselleLeeOSI** [comment]
> I'm still waiting for one of the 4 PRs that point to this repository to finish (Metrics), the other 3 are there.
> 
> Since this is a PR into a branch, this cleanup can be merged into it.

Hi Thomas, I think I'll wait for that other controller content to come in. Now if you want us to look at the source comments and suggest edits, do you want one of the writers to go do it or just mention to you what we'd like refined (parameter description, summary of the method, etc.)?

**Comment by tommarkosi** [comment]
I'm asking my team what they prefer and I'll get back to you! Thanks!

**Comment by tommarkosi** [comment]
So it would be possible for one of the writers to do the language magic directly in our repositories via PR and we approve/make sure the message is correct? I believe I've seen that in other repositories like `Identity-services` and that is the workflow we would prefer (if possible).

**Comment by tommarkosi** [comment]
FYI, the 4th and final markdown document is now in place in the branch.

**Comment by tommarkosi** [comment]
Closing to make a cleaner PR, this one is having trouble pulling in the new markdown

**Comment by GiselleLeeOSI** [comment]
> So it would be possible for one of the writers to do the language magic 😄 directly in our repositories via PR and we approve/make sure the message is correct? I believe I've seen that in other repositories like `Identity-services` and that is the workflow we would prefer (if possible).

Yes! That's recommended. The writer to do the work for operations would be Mark Rogers.

**Comment by GiselleLeeOSI** [comment]
@tommarkosi, do you want me to merge this or wait? I notice you closed the PR.

**Comment by tommarkosi** [comment]
I closed this one due to a git issue and opened this one:  https://github.com/osisoft/OCS-Docs/pull/494

**Pull request closed without merging**
