### PR TITLE
There is no Status property, it's State, it was trowing an exception

### PR DESCRIPTION
**Pull request by FreeJules**

### CODE REVIEW

**Comment by osimarkrogers** [comment]
Change is clear.  Merged to master.

**Comment by FreeJules** [comment]
> Change is clear, but getting a conflict message. Have to reconcile before I can merge.

**Comment by FreeJules** [comment]
@osimarkrogers Fixed the conflict, OK to merge now

**Comment by osimarkrogers** [comment]
OK, Julija…will do!

**Comment by osimarkrogers** [comment]
Julija resolved conflict.  Merging to master.

**Comment by osimarkrogers** [comment]
Merged.

**Pull request merged**
