### PR TITLE
Aflores 257476 update screenshots

### PR DESCRIPTION
**Pull request by afloresOSI**
PR for updated screenshots.

### CODE REVIEW

**Review by VictoriaTouati-AVEVA — APPROVED** [review]
Changes look legit!

**Review by osisoft-mbishop — APPROVED** [review]
Looks good!

**Comment by afloresOSI** [comment]
Closing because I picked the wrong branch to publish to. Created 692 to merge to development.

**Review by osisoft-mbishop — COMMENTED** [review]
@afloresOSI , changes look good!

**Pull request closed without merging**
