### PR TITLE
Operations - Update for new filenames

### PR DESCRIPTION
**Pull request by tommarkosi**

### CODE REVIEW

**Review by GiselleLeeOSI — APPROVED** [review]
This is so the files that are generated based on the new mapping file are the only ones coming through the pipeline?

**Comment by tommarkosi** [comment]
Correct, the files have new names based on the new mappings.

**Comment by GiselleLeeOSI** [comment]
> Correct, the files have new names based on the new mappings.

Let me know if you want me to merge.

**Comment by tommarkosi** [comment]
Yes please, this will keep this branch ready to go.

**Pull request merged**
